### ISSUE TITLE
Cannot install copydog on OS X

### ISSUE THREAD

**Issue by m-baumgartner** [coagulant/copydog#3]
When installing copydog on my mac I encounter the following error : 

> Collecting copydog
> Requirement already satisfied (use --upgrade to upgrade): requests==0.13.6 in /Library/Python/2.7/site-packages (from copydog)
> Requirement already satisfied (use --upgrade to upgrade): texttable==0.8.1 in /Library/Python/2.7/site-packages (from copydog)
> Requirement already satisfied (use --upgrade to upgrade): PyYAML==3.10 in /Library/Python/2.7/site-packages (from copydog)
> Requirement already satisfied (use --upgrade to upgrade): docopt==0.4.1 in /Library/Python/2.7/site-packages (from copydog)
> Requirement already satisfied (use --upgrade to upgrade): python-daemon==1.6 in /Library/Python/2.7/site-packages (from copydog)
> Collecting python-dateutil==2.1 (from copydog)
> Collecting pytz==2012c (from copydog)
> Requirement already satisfied (use --upgrade to upgrade): redis==2.6.2 in /Library/Python/2.7/site-packages (from copydog)
> Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from python-daemon==1.6->copydog)
> Requirement already satisfied (use --upgrade to upgrade): lockfile>=0.9 in /Library/Python/2.7/site-packages (from python-daemon==1.6->copydog)
> Requirement already satisfied (use --upgrade to upgrade): six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from python-dateutil==2.1->copydog)
> Installing collected packages: python-dateutil, pytz, copydog
>   Found existing installation: python-dateutil 1.5
>     Uninstalling python-dateutil-1.5:
> Exception:
> Traceback (most recent call last):
>   File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 211, in main
>     status = self.run(options, args)
>   File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 311, in run
>     root=options.root_path,
>   File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 640, in install
>     requirement.uninstall(auto_confirm=True)
>   File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 716, in uninstall
>     paths_to_remove.remove(auto_confirm)
>   File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 125, in remove
>     renames(path, new_path)
>   File "/Library/Python/2.7/site-packages/pip/utils/**init**.py", line 315, in renames
>     shutil.move(old, new)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 299, in move
>     copytree(src, real_dst, symlinks=True)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
>     raise Error, errors
> Error: [('/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/**init**.py', '/var/folders/g3/2kz585hj6fn7y6xssftzn1740000gn/T/pip-eu1mHM-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/**init**.py', "[Errno 1] Operation not permitted: '/var/folders/g3/2kz585hj6fn7y6xssftzn1740000gn/T/pip-eu1mHM-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/**init**.py'"), 

It goes on and on again..

Using sudo doesn't make a difference

**Comment by m-baumgartner** [comment]
Must be a version conflict with packages shipped by default with Mac OS. 
It works well in a `virtualenv`

**Comment by scvdance** [comment]
I am having the same problem here. Can someone help me solve this problem?

**Comment by m-baumgartner** [comment]
Honestly I gave up installing it on my OSX environment. 
It was just for testing purposes anyway. I did my testing inside a `virtualenv`( see [here](http://docs.python-guide.org/en/latest/dev/virtualenvs/) ).

**Comment by scvdance** [comment]
@m-baumgartner  Thanks a lot, bro. virtualenv worked for me.
